CREATE TABLE category_syokuhin
(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,c_Id INTEGER,name text)/
INSERT INTO category_syokuhin(c_Id,name)values(1,"ごはん")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"パン")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"めん")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"その他の穀物")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"芋")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"炭水化物の多い野菜と種実")/
INSERT INTO category_syokuhin(c_Id,name)values(1,"豆")/
INSERT INTO category_syokuhin(c_Id,name)values(2,"くだもの")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"脂質の少ない魚")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"脂質のやや多い魚")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"脂質の多い魚")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"貝")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"いか・たこ・その他")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"大豆とその製品")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"卵")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"チーズ")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"牛肉")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"豚肉")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"とり肉")/
INSERT INTO category_syokuhin(c_Id,name)values(3,"その他の肉・加工品")/
INSERT INTO category_syokuhin(c_Id,name)values(4,"牛乳と乳製品")/
INSERT INTO category_syokuhin(c_Id,name)values(5,"油脂")/
INSERT INTO category_syokuhin(c_Id,name)values(5,"脂質の多い種実")/
INSERT INTO category_syokuhin(c_Id,name)values(5,"多脂性食品")/
INSERT INTO category_syokuhin(c_Id,name)values(6,"緑黄色野菜")/
INSERT INTO category_syokuhin(c_Id,name)values(6,"淡色野菜")/
INSERT INTO category_syokuhin(c_Id,name)values(6,"海藻・こんにゃく")/
INSERT INTO category_syokuhin(c_Id,name)values(6,"きのこ類")/
INSERT INTO category_syokuhin(c_Id,name)values(7,"みそ・みりん・砂糖など")