CREATE TABLE syokuhin
(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,cs_Id INTEGER,name text,unit INTEGER)/
INSERT INTO syokuhin(cs_Id,name,unit)values(1,"ごはん",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(1,"かゆ（全がゆ）",110)/
INSERT INTO syokuhin(cs_Id,name,unit)values(1,"赤飯",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(1,"もち",35)/
INSERT INTO syokuhin(cs_Id,name,unit)values(1,"米",25)/
INSERT INTO syokuhin(cs_Id,name,unit)values(2,"食パン",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(2,"フランスパン",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(2,"ナン",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(2,"ロールパン",25)/
INSERT INTO syokuhin(cs_Id,name,unit)values(2,"クロワッサン",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"うどん(ゆで)",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"そば(ゆで)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"スパゲティ(ゆで)",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"中華めん(蒸し)",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"うどん(生)",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"うどん(干し)",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(3,"スパゲティ(干し)",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"とうもろこし",90)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"ギョウザの皮",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"はるさめ(干し)",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"オートミール(干し)",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"乾パン",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"クラッカー",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"コーンフレーク",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"小麦粉",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"片栗粉",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(4,"麩",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"里芋",140)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"長芋",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"じゃが芋",110)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"やつがしら",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"やまのいも",70)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"さつまいも",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"焼きいも",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(5,"乾燥いも",25)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"れんこん",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"スイートコーン(缶詰)",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"西洋かぼちゃ",90)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"ゆりね",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"くり",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"甘ぐり",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(6,"ぎんなん",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(7,"グリーンピース",90)/
INSERT INTO syokuhin(cs_Id,name,unit)values(7,"そら豆",70)/
INSERT INTO syokuhin(cs_Id,name,unit)values(7,"あずき(ゆで)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(7,"あずき(乾)",25)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"いちご",250)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"スターフルーツ",250)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"すいか",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"なし",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"メロン",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"グレープフルーツ",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"バレンシアオレンジ",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"ポンカン",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"みかん",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"レモン",150)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"キウイフルーツ",150)/
INSERT INTO syokuhin(cs_Id,name,unit)values(8,"パイナップル",150)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"あんこう",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"えい",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"キス",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"キングクリップ",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"しらうお",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"ふぐ",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"メルルーサ",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"しいら",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(9,"とびうお",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(10,"あじ",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(10,"かじき",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(10,"かんぱち",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(10,"たい", 60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(10,"まぐろ(赤身)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(11,"あなご",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(11,"さば",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(11,"うなぎ",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(11,"ぶり",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(12,"あさり",260)/
INSERT INTO syokuhin(cs_Id,name,unit)values(12,"はまぐり",200)/
INSERT INTO syokuhin(cs_Id,name,unit)values(12,"しじみ",160)/
INSERT INTO syokuhin(cs_Id,name,unit)values(12,"ほたてがい",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(12,"さざえ",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"なまこ",340)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"かに",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"いか",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"たこ",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"あまえび",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"しばえび",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"ブラックタイガー",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"伊勢えび",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"うに",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(13,"すっぽん",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"豆腐(絹ごし)",140)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"豆腐(木綿)",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"焼き豆腐",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"おから",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"枝豆(ゆで)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"生揚げ",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"納豆",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(14,"ゆで大豆",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(15,"鶏卵",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(15,"うずら卵",50)/
INSERT INTO syokuhin(cs_Id,name,unit)values(15,"卵白",160)/
INSERT INTO syokuhin(cs_Id,name,unit)values(15,"卵黄",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(15,"卵どうふ",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(16,"カテージチーズ",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(16,"ナチュラルチーズ",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(16,"プロセスチーズ",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(16,"チーズスプレッド",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(17,"かた・そともも・ヒレ・もも・ランプ",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(17,"かたロース・サーロイン",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(17,"ひき肉",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(17,"ヒレ・もも",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(17,"かた・そともも・ランプ",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(18,"ヒレ・もも",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(18,"かた・かたロース・そともも・ロース",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(18,"ひき肉",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(19,"ささみ・むね(皮なし)",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(19,"もも(皮なし)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(19,"むね",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(19,"むね・もも・手羽",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(19,"ひき肉",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"砂肝(とり)",80)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"牛すじ",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"レバー(牛・豚・鳥の肝臓)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"うま・かも・七面鳥",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"あいがも",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"タン",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"ロースハム",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"ソーセージ(ウィンナー)",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"ショルダーベーコン",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(20,"焼き豚",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"脱脂乳",240)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"普通牛乳",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"加工乳(低脂肪)",160)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"加工乳(濃厚)",100)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"ヨーグルト(脱脂加糖)",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"ヨーグルト(全脂無糖)",120)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"無糖練乳(エバミルク)",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"脱脂粉乳(スキムミルク)",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(21,"全粉乳",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"ドレッシング",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"ごま油",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"植物油",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"バター",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"マーガリン",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"マヨネーズ",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"牛脂",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(22,"ラード",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(23,"ごま",15)/
INSERT INTO syokuhin(cs_Id,name,unit)values(23,"アーモンド",15)/
INSERT INTO syokuhin(cs_Id,name,unit)values(23,"ピーナッツ",15)/
INSERT INTO syokuhin(cs_Id,name,unit)values(23,"くるみ",10)/
INSERT INTO syokuhin(cs_Id,name,unit)values(24,"アボカド",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(24,"クリームチーズ",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(24,"豚バラ肉",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(24,"ベーコン",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(24,"とり皮",15)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"あしたば",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"グリーンアスパラガス",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"おかひじき",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"おくら",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"からしな",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"かぼちゃ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"茎にんにく",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"クレソン",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"ケール",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"小松菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"さやいんげん",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"さやえんどう",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"サラダ菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"三東菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"ししとうがらし",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"しそ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"春菊",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"せり",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"だいこん葉",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"高菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"たらの芽",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"チンゲンサイ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"トマト",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"にら",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"人参",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"野沢菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"パセリ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"葉ねぎ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"ピーマン(青・赤)",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"ブロッコリー",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"ほうれん草",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"みつば",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"モロヘイヤ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"リーキ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(25,"わけぎ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"ホワイトアスパラ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"うど",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"枝豆",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"かぶ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"カリフラワー",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"かんぴょう",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"きく",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"キャベツ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"きゅうり",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"グリーンピース",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"くわい",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"ごぼう",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"しょうが",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"ズッキーニ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"セロリ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"そら豆",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"大根",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"たけのこ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"玉ねぎ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"冬瓜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"とうもろこし",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"なす",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"ゴーヤ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"にんにく",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"葉深ねぎ",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"白菜",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"二十日だいこん",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"ピーマン(黄)",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"みょうが",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"もやし",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"レタス",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(26,"れんこん",300)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"あおのり",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"いわのり",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"寒天",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"こんぶ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"ところてん",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"のり",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"ひじき",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"もずく",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"わかめ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"こんにゃく",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(27,"しらたき",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"えのき茸",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"エリンギ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"しいたけ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"しめじ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"なめこ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"ひらたけ",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"舞茸",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"マッシュルーム",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(28,"松茸",0)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"オイスターソース",75)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"濃厚ソース",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"トマトケチャップ",60)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"みそ",40)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"酒かす",35)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"みりん",35)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"メープルシロップ",30)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"はちみつ",25)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"砂糖",20)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"カレールウ",15)/
INSERT INTO syokuhin(cs_Id,name,unit)values(29,"ハヤシルウ",15)

